version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      dev-tooling:
        patterns:
          - '@biomejs/*'
          - '@commitlint/*'
          - husky
          - lint-staged
          - typescript

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /infra
    schedule:
      interval: weekly
