import { CHAIN_ID_MAINNET } from '@setcode/shared/constants';

// Catalogue of EVM chains where EIP-7702 has shipped (Pectra-equivalent
// activation). Surfaced in the home-page table so users see breadth before
// pasting an address. Only `monitored: true` chains hit the watcher's
// `/check` API today — the rest resolve as "Not Detected" client-side until
// the indexer grows network coverage (see docs/ROADMAP.md "L2 support").
export interface ChainMeta {
  // Canonical chain id (used as the Vue key and for future per-chain API
  // calls).
  id: number;
  // Stable slug for analytics, route params, etc. — never displayed.
  slug: string;
  // User-facing label.
  name: string;
  // Coarse grouping. The home page renders mainnets first, then a separate
  // "Testnets" table at the bottom with faded icons so production rows
  // stay the visual anchor.
  group: 'mainnet' | 'testnet';
  // Whether the watcher actually has indexer state for this chain. False
  // chains skip the network round-trip and resolve to "Not Detected" after
  // a short delay so the UI feels uniformly responsive.
  monitored: boolean;
  // Visual identity. 'eth' renders the Ethereum diamond; 'mark' renders a
  // colored circle with a 1–2 char glyph (good enough for L2s without
  // shipping vector logos for each).
  icon: 'eth' | 'mark';
  mark?: string;
  bg?: string;
  fg?: string;
}

// Brand-pair lookup for L2s that share a parent (e.g. Base + Base Sepolia).
// Avoids redundant per-row literals; keeps testnet visuals trivially in
// sync with their mainnet sibling.
const brand = {
  bnb: { mark: 'B', bg: '#F0B90B', fg: '#1A1A1A' },
  base: { mark: 'B', bg: '#0052FF', fg: '#FFFFFF' },
  op: { mark: 'OP', bg: '#FF0420', fg: '#FFFFFF' },
  arb: { mark: 'A', bg: '#28A0F0', fg: '#FFFFFF' },
  polygon: { mark: 'P', bg: '#8247E5', fg: '#FFFFFF' },
  unichain: { mark: 'U', bg: '#F50DB4', fg: '#FFFFFF' },
  linea: { mark: 'L', bg: '#121212', fg: '#61DFFF' },
  gnosis: { mark: 'G', bg: '#04795B', fg: '#FFFFFF' },
  avalanche: { mark: 'AV', bg: '#E84142', fg: '#FFFFFF' },
  scroll: { mark: 'SC', bg: '#FFEEDA', fg: '#101010' },
  hyperliquid: { mark: 'H', bg: '#97FCE4', fg: '#072723' },
  monad: { mark: 'MO', bg: '#836EF9', fg: '#FFFFFF' },
  ink: { mark: 'IK', bg: '#1E1E1E', fg: '#FFFFFF' },
  zora: { mark: 'Z', bg: '#000000', fg: '#FFFFFF' },
  soneium: { mark: 'SO', bg: '#444444', fg: '#FFFFFF' },
  mode: { mark: 'MD', bg: '#DFFE00', fg: '#000000' },
  berachain: { mark: 'BR', bg: '#814625', fg: '#FFFFFF' },
  celo: { mark: 'C', bg: '#FCFF52', fg: '#000000' },
  filecoin: { mark: 'F', bg: '#0090FF', fg: '#FFFFFF' },
  mantle: { mark: 'MA', bg: '#000000', fg: '#FFFFFF' },
  lisk: { mark: 'LK', bg: '#2347FF', fg: '#FFFFFF' },
  neon: { mark: 'N', bg: '#00C2A8', fg: '#FFFFFF' },
  xrpl: { mark: 'X', bg: '#00AAE4', fg: '#FFFFFF' },
} as const;

export const CHAINS: readonly ChainMeta[] = [
  // ---- Mainnets ----------------------------------------------------------
  {
    id: CHAIN_ID_MAINNET,
    slug: 'eth',
    name: 'Ethereum Mainnet',
    group: 'mainnet',
    monitored: true,
    icon: 'eth',
  },
  {
    id: 56,
    slug: 'bnb',
    name: 'BNB',
    group: 'mainnet',
    monitored: false,
    icon: 'mark',
    ...brand.bnb,
  },
  {
    id: 8453,
    slug: 'base',
    name: 'Base',
    group: 'mainnet',
    monitored: false,
    icon: 'mark',
    ...brand.base,
  },
  {
    id: 10,
    slug: 'op',
    name: 'Optimism',
    group: 'mainnet',
    monitored: false,
    icon: 'mark',
    ...brand.op,
  },
  {
    id: 42161,
    slug: 'arb',
    name: 'Arbitrum One',
    group: 'mainnet',
    monitored: false,
    icon: 'mark',
    ...brand.arb,
  },
  {
    id: 137,
    slug: 'polygon',
    name: 'Polygon PoS',
    group: 'mainnet',
    monitored: false,
    icon: 'mark',
    ...brand.polygon,
  },
  {
    id: 100,
    slug: 'gnosis',
    name: 'Gnosis',
    group: 'mainnet',
    monitored: false,
    icon: 'mark',
    ...brand.gnosis,
  },
  {
    id: 43114,
    slug: 'avalanche',
    name: 'Avalanche',
    group: 'mainnet',
    monitored: false,
    icon: 'mark',
    ...brand.avalanche,
  },
  {
    id: 130,
    slug: 'unichain',
    name: 'Unichain',
    group: 'mainnet',
    monitored: false,
    icon: 'mark',
    ...brand.unichain,
  },
  {
    id: 59144,
    slug: 'linea',
    name: 'Linea',
    group: 'mainnet',
    monitored: false,
    icon: 'mark',
    ...brand.linea,
  },
  {
    id: 534352,
    slug: 'scroll',
    name: 'Scroll',
    group: 'mainnet',
    monitored: false,
    icon: 'mark',
    ...brand.scroll,
  },
  {
    id: 999,
    slug: 'hyperliquid',
    name: 'Hyperliquid',
    group: 'mainnet',
    monitored: false,
    icon: 'mark',
    ...brand.hyperliquid,
  },
  {
    id: 57073,
    slug: 'ink',
    name: 'Ink',
    group: 'mainnet',
    monitored: false,
    icon: 'mark',
    ...brand.ink,
  },
  {
    id: 7777777,
    slug: 'zora',
    name: 'Zora',
    group: 'mainnet',
    monitored: false,
    icon: 'mark',
    ...brand.zora,
  },
  {
    id: 1868,
    slug: 'soneium',
    name: 'Soneium',
    group: 'mainnet',
    monitored: false,
    icon: 'mark',
    ...brand.soneium,
  },
  {
    id: 34443,
    slug: 'mode',
    name: 'Mode',
    group: 'mainnet',
    monitored: false,
    icon: 'mark',
    ...brand.mode,
  },
  {
    id: 80094,
    slug: 'berachain',
    name: 'Berachain',
    group: 'mainnet',
    monitored: false,
    icon: 'mark',
    ...brand.berachain,
  },
  {
    id: 42220,
    slug: 'celo',
    name: 'Celo',
    group: 'mainnet',
    monitored: false,
    icon: 'mark',
    ...brand.celo,
  },
  {
    id: 314,
    slug: 'filecoin',
    name: 'Filecoin',
    group: 'mainnet',
    monitored: false,
    icon: 'mark',
    ...brand.filecoin,
  },
  {
    id: 5000,
    slug: 'mantle',
    name: 'Mantle',
    group: 'mainnet',
    monitored: false,
    icon: 'mark',
    ...brand.mantle,
  },
  {
    id: 1135,
    slug: 'lisk',
    name: 'Lisk',
    group: 'mainnet',
    monitored: false,
    icon: 'mark',
    ...brand.lisk,
  },
  {
    id: 245022934,
    slug: 'neon',
    name: 'NEON EVM',
    group: 'mainnet',
    monitored: false,
    icon: 'mark',
    ...brand.neon,
  },
  {
    id: 1440000,
    slug: 'xrpl',
    name: 'XRPL EVM',
    group: 'mainnet',
    monitored: false,
    icon: 'mark',
    ...brand.xrpl,
  },

  // ---- Testnets ----------------------------------------------------------
  {
    id: 11155111,
    slug: 'sepolia',
    name: 'Ethereum Sepolia',
    group: 'testnet',
    monitored: false,
    icon: 'eth',
  },
  {
    id: 17000,
    slug: 'holesky',
    name: 'Ethereum Holesky',
    group: 'testnet',
    monitored: false,
    icon: 'eth',
  },
  {
    id: 560048,
    slug: 'hoodi',
    name: 'Ethereum Hoodi',
    group: 'testnet',
    monitored: false,
    icon: 'eth',
  },
  {
    id: 97,
    slug: 'bnb-testnet',
    name: 'BNB Testnet',
    group: 'testnet',
    monitored: false,
    icon: 'mark',
    ...brand.bnb,
  },
  {
    id: 84532,
    slug: 'base-sepolia',
    name: 'Base Sepolia',
    group: 'testnet',
    monitored: false,
    icon: 'mark',
    ...brand.base,
  },
  {
    id: 11155420,
    slug: 'op-sepolia',
    name: 'Optimism Sepolia',
    group: 'testnet',
    monitored: false,
    icon: 'mark',
    ...brand.op,
  },
  {
    id: 421614,
    slug: 'arb-sepolia',
    name: 'Arbitrum Sepolia',
    group: 'testnet',
    monitored: false,
    icon: 'mark',
    ...brand.arb,
  },
  {
    id: 80002,
    slug: 'polygon-amoy',
    name: 'Polygon Amoy',
    group: 'testnet',
    monitored: false,
    icon: 'mark',
    ...brand.polygon,
  },
  {
    id: 10200,
    slug: 'gnosis-chiado',
    name: 'Gnosis Chiado',
    group: 'testnet',
    monitored: false,
    icon: 'mark',
    ...brand.gnosis,
  },
  {
    id: 43113,
    slug: 'avalanche-fuji',
    name: 'Avalanche Fuji',
    group: 'testnet',
    monitored: false,
    icon: 'mark',
    ...brand.avalanche,
  },
  {
    id: 1301,
    slug: 'unichain-sepolia',
    name: 'Unichain Sepolia',
    group: 'testnet',
    monitored: false,
    icon: 'mark',
    ...brand.unichain,
  },
  {
    id: 534351,
    slug: 'scroll-sepolia',
    name: 'Scroll Sepolia',
    group: 'testnet',
    monitored: false,
    icon: 'mark',
    ...brand.scroll,
  },
  {
    id: 998,
    slug: 'hyperliquid-testnet',
    name: 'Hyperliquid Testnet',
    group: 'testnet',
    monitored: false,
    icon: 'mark',
    ...brand.hyperliquid,
  },
  {
    id: 10143,
    slug: 'monad-testnet',
    name: 'Monad Testnet',
    group: 'testnet',
    monitored: false,
    icon: 'mark',
    ...brand.monad,
  },
  {
    id: 763373,
    slug: 'ink-sepolia',
    name: 'Ink Sepolia',
    group: 'testnet',
    monitored: false,
    icon: 'mark',
    ...brand.ink,
  },
  {
    id: 999999999,
    slug: 'zora-sepolia',
    name: 'Zora Sepolia',
    group: 'testnet',
    monitored: false,
    icon: 'mark',
    ...brand.zora,
  },
  {
    id: 1946,
    slug: 'soneium-minato',
    name: 'Soneium Minato',
    group: 'testnet',
    monitored: false,
    icon: 'mark',
    ...brand.soneium,
  },
  {
    id: 919,
    slug: 'mode-sepolia',
    name: 'Mode Sepolia',
    group: 'testnet',
    monitored: false,
    icon: 'mark',
    ...brand.mode,
  },
  {
    id: 80069,
    slug: 'berachain-bepolia',
    name: 'Berachain Bepolia',
    group: 'testnet',
    monitored: false,
    icon: 'mark',
    ...brand.berachain,
  },
  {
    id: 11142220,
    slug: 'celo-sepolia',
    name: 'Celo Sepolia',
    group: 'testnet',
    monitored: false,
    icon: 'mark',
    ...brand.celo,
  },
  {
    id: 314159,
    slug: 'filecoin-calibration',
    name: 'Filecoin Calibration',
    group: 'testnet',
    monitored: false,
    icon: 'mark',
    ...brand.filecoin,
  },
  {
    id: 5003,
    slug: 'mantle-sepolia',
    name: 'Mantle Sepolia',
    group: 'testnet',
    monitored: false,
    icon: 'mark',
    ...brand.mantle,
  },
  {
    id: 4202,
    slug: 'lisk-sepolia',
    name: 'Lisk Sepolia',
    group: 'testnet',
    monitored: false,
    icon: 'mark',
    ...brand.lisk,
  },
  {
    id: 245022926,
    slug: 'neon-devnet',
    name: 'NEON EVM Devnet',
    group: 'testnet',
    monitored: false,
    icon: 'mark',
    ...brand.neon,
  },
  {
    id: 1449000,
    slug: 'xrpl-testnet',
    name: 'XRPL EVM Testnet',
    group: 'testnet',
    monitored: false,
    icon: 'mark',
    ...brand.xrpl,
  },
];

export function useChainCatalog() {
  const mainnets = CHAINS.filter((c) => c.group === 'mainnet');
  const testnets = CHAINS.filter((c) => c.group === 'testnet');
  return { chains: CHAINS, mainnets, testnets };
}
